name: Build War File

on:
  push:
    branches:
      - main
      - W_*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17.0.11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17.0.11'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip --file pom.xml

    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: capstone-war
        overwrite: true
        path: target/*.war  

    - name: Run Spring Boot Tests
      run: mvn test -Dtest="*Test"

    - name: Run Tests and Generate Coverage
      run: mvn jacoco:report

      # Upload JaCoCo coverage report
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco