name: Build War File

on:
  push:
    branches:
      - main
      - W_*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17.0.12
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17.0.12'
        cache: maven
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip --file pom.xml

    - name: Upload WAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: capstone-war
        overwrite: true
        path: target/*.war  

    - name: Execute Shell Script
      run: |
        echo "Setting up environment variables"
        export DB_URL="jdbc:mysql://psugvsecapstone-psugvsecapstone.f.aivencloud.com:26571"
        export DB_USERNAME="capstone"
        export DB_PASSWORD="capstone"
        echo "DB_URL=$DB_URL" >> $GITHUB_ENV
        echo "DB_USERNAME=$DB_USERNAME" >> $GITHUB_ENV
        echo "DB_PASSWORD=$DB_PASSWORD" >> $GITHUB_ENV
        echo "Environment variables are set!"

#    - name: Run Spring Boot Tests
#      run: mvn test -Dtest=All in Capstone